### ISSUE TITLE
CS_REST_BaseSerialiser constructor expects parameters, but are never defined

### ISSUE THREAD

**Issue by JCquence** [campaignmonitor/createsend-php#53]
CS_REST_General::exchange_token creates a CS_REST_DoNothingSerialiser (line 64), but this constructor expects a $log parameter (class/serialissation.php:19), which will throw an error when fetching a refresh token

**Comment by emilebourquin** [comment]
I am experiencing this warning also. I'm not sure if the correct solution is:

changing the exchange_token function's call to "new CS_REST_Wrapper_Base" to look like this:

`$wrap = new CS_REST_Wrapper_Base(
                NULL, 'https', CS_REST_LOG_NONE, CS_HOST, NULL,
                new CS_REST_DoNothingSerialiser(NULL), NULL);`

or making the CS_REST_BaseSerialiser __construct function signature look like this:

`function __construct($log = NULL) {`

or something else entirely.

**Comment by feydan** [comment]
I'm running into the same issue.  I've been forced to try and work around it by making these calls manually instead of relying on the library.

**Comment by feydan** [comment]
Here is a link to the forum message if you want to track it or comment with additional details: https://www.campaignmonitor.com/forums/topic/9004/php-wrapper-broken-for-php-versions-5/

**Comment by ashitvora** [comment]
I'm still running into the same issue :(

**Comment by feydan** [comment]
This fix was merged into master -- I just locked composer into the latest commit, and it fixed this issue.

**Comment by ashitvora** [comment]
@feydan How do I do that?

**Comment by feydan** [comment]
This is how I have it in my composer.json under 'require': 
`"campaignmonitor/createsend-php": "dev-master#0617d7c451c5004cedf3142e491566691d217661"`

**Comment by leemtm** [comment]
This is still an issue in 2.5.5 (and 2.5.4, and 2.5.3):

2017/03/27 13:23:02 [error] 2630#2630: *133297 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function CS_REST_BaseSerialiser::__construct(), 0 passed in [...]wp-content/plugins/forms-for-campaign-monitor/createsend-php/class/base_classes.php on line 193 and exactly 1 expected in [...]wp-content/plugins/forms-for-campaign-monitor/createsend-php/class/serialisation.php:23
Stack trace:
#0 [...]wp-content/plugins/forms-for-campaign-monitor/createsend-php/class/base_classes.php(193): CS_REST_BaseSerialiser->__construct()
#1 [...]wp-content/plugins/forms-for-campaign-monitor/forms/core/CampaignMonitor.php(38): CS_REST_Wrapper_Base->refresh_token()
#2 [...]wp-content/plugins/forms-for-campaign-monitor/forms/core/Application.php(137): forms\core\CampaignMonitor->refresh_token(Array)
#3 [...]wp-content/plugins/forms-for" while reading response header from upstream, client: 95.121.27.30, server: [...], request: "GET /wp-admin/plugins.php?activate=true&plugin_status=all&paged=1&s= HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.1-fpm.sock:", host: "[...]"

This Plugin has been a repeated disappointment recently (what with the jQuery bugs). When will this issue be resolved? Does Campaign Monitor even care about all their WordPress customers?
